name: Notify Telegram with Decoded Log (Base64)

on:
  push:
    paths:
      - log_token.txt

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode Base64 log
        id: decode
        run: |
          decoded=$(base64 -d log_token.txt | tr -d '\r')
          echo "log<<EOF" >> $GITHUB_OUTPUT
          echo "$decoded" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            --data-urlencode "text=📥 Log mới (giải mã):%0A<pre>${{ steps.decode.outputs.log }}</pre>" \
            -d parse_mode=HTML
